version: '2'
services:
  client:
    container_name: sto-client
    networks: 
        - sto
    image: coinvault/savetheocean
    ports: 
        - 5032:5000
        - 4555:4555
  nako:
    container_name: sto-nako
    networks: 
        - sto
    image: coinvault/nako:core
    command: sto
    ports: 
        - 9032:9000
    depends_on:
        - mongo
        - client
  mongo:
    container_name: sto-mongo
    networks: 
        - sto
    image: mongo:3.2
networks:
    sto:
      driver: bridge
